#!/bin/bash -e
# Get the git status of the charms -- i.e. what has changed

charms=$(cd charms && ls -d1 *)

for charm in $charms; do
    echo "===== $charm git status ====="
    (
        if [ -d "charms/$charm" ]; then
            charm_type="$(./what-is charms/$charm)"
            case $charm_type in
                classic-zaza)
                    echo "$charm is a classic charm."
                    ;;

                source-zaza)
                    echo "$charm is a source charm (reactive)."
                    ;;
            esac

            cd "charms/$charm"
            git status --short --branch
        fi
    )
done

