#!/bin/bash -e
# Get the git status of the charms -- i.e. what has changed

charms="$(cat charms.txt)"

for charm in $charms; do
    if [ ! -d "charms/$charm" ]; then
        echo "Use ./get-charms master to clone the charm dirs first ($charm not found)"
        #exit 1
    fi
done

for charm in $charms; do
    echo "===== $charm git status ====="
    (
        if [ -d "charms/$charm" ]; then
            charm_type="$(./what-is charms/$charm)"
            case $charm_type in
                classic-zaza | classic-amulet)
                    echo "$charm is a classic charm."
                    ;;

                source-zaza | source-amulet)
                    echo "$charm is a source charm (reactive)."
                    ;;
            esac

            cd "charms/$charm"
            git diff --color=always
        fi
    )
done

