#!/bin/bash
script_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"


charm_type="$($script_dir/what-is .)"
echo "===== $charm_type ====="
case $charm_type in
    classic-zaza)
        echo "Updating classic charm."
        make sync
        grep ceph-sync Makefile && make ceph-sync ||:
        ;;
    *)
        echo "Nothing to do."
        ;;
esac
