#!/bin/bash -e
#  Build only reactive charms with build.lock files; requires the charms to have been synced using
# ./get-charms

charms="$(cat charms.txt)"
_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"


for charm in $charms; do
    echo "===== $charm ====="
    full_charm="cs:~openstack-charmers/$charm"
    id_revision=$(charm show "$full_charm" --channel stable id | grep -e "Id: $full_charm" | xargs | cut -d " " -f 2)
    if [ -z "$id_revision" ]; then
        echo "Nothing to do."
    else
        echo "Charm revision is $id_revision"

        # now get the resources:
        resources_line=$(charm show "$full_charm" resources | yq eval '.resources[] | "--resource " + .Name + "-" + .Revision' - | tr '\n' ' ')
        echo "resource line is: $resources_line"

        # now try to release it.
        echo "Running >> charm release $id_revision $resources_line --channel=candidate"
        charm release $id_revision $resources_line --channel=candidate
        echo "Running >> charm grant $full_charm --channel candidate --acl read everyone"
        charm grant $full_charm --channel candidate --acl read everyone
    fi
done

