#!/bin/bash -e
#  Do a reset in all the charms; great for undoing damage and starting again.

charms=$(cd charms && ls -d1 *)
branch=$1

if [ -z "$branch" ]; then
    echo "Please provide the branch name as the param."
    exit 1
fi

for charm in $charms; do
    if [ ! -d "charms/$charm" ]; then
        echo "Use ./get-charms master to clone the charm dirs first ($charm not found)"
        exit 1
    fi
done

for charm in $charms; do
    charm_type="$(./what-is charms/$charm)"
    echo "===== $charm ($charm_type) ====="
    (
        cd "charms/$charm"
        git reset --hard $branch
    )
done

