#!/bin/bash -e
#  Clean-up the build and .tox directories after a build for reactive charms.
#  This is used after a build step when making reproducible reactive charms.

charms="$(cat charms.txt)"

for charm in $charms; do
    if [ ! -d "charms/$charm" ]; then
        echo "Use ./get-charms master to clone the charm dirs first ($charm not found)"
        exit 1
    fi
done

for charm in $charms; do
    charm_type="$(./what-is charms/$charm)"
    echo "===== $charm ($charm_type) ====="
    (
        cd "charms/$charm"
        case $charm_type in
            source-zaza | source-amulet)
                rm -rf build
                rm -rf .tox
                ;;
            classic-zaza | classic-amulet)
                echo "NOOP on $charm as it is a classic charm."
                ;;
            *)
                echo "UNKNOWN TYPE" && exit 1
                ;;
        esac

    )
done

