#!/bin/bash -e
# do one rebuild of a charm in the ./charms directory.  Name the directory as
# the first parameter

charm=$1

if [[ ! -d "charms/$charm" ]]; then
    echo "_do_one_rebuild <charm>"
    echo "  where <charm> is a directory in the ./charms directory"
    exit 1
fi

charm_type="$(./what-is charms/$charm)"
echo "===== $charm ($charm_type) ====="
(
    # Do a charm-helpers sync where possible
    cd "charms/$charm"
    case $charm_type in
        source-zaza | source-amulet)
            # update/add the rebuild file to trigger a rebuild
            uuid=$(uuid)
            echo -e "# This file is used to trigger rebuilds\n# when dependencies of the charm change,\n# but nothing in the charm needs to.\n# simply change the uuid to something new\n$uuid" > ./rebuild
            ;;
        classic-zaza | classic-amulet)
            echo "NOOP on $charm as it is a classic charm."
            ;;
        *)
            echo "UNKNOWN TYPE" && exit 1
            ;;
    esac

)
