#!/bin/bash -e
#  Update tox.ini files from global/*.  Assumes git clones have already
#  been performed.  Does not commit, push, or submit/review.
#  See `batch-example` for usage as a batch of charm updates.

script_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"
charms=$(cd charms && ls -d1 *)

for charm in $charms; do
    (
        cd "charms/$charm"
        $script_dir/_update-tox-files-single
    )
done
