#!/bin/bash -e
#  Sync charm-helpers and ceph helpers where applicable.  Assumes git clones
#  have already been performed.  Does not commit, push, or submit/review.
#  See `batch-example` for usage as a batch of charm updates.

charms=$(cd charms && ls -d1 *)

for charm in $charms; do
    charm_type="$(./what-is charms/$charm)"
    echo "===== $charm ($charm_type) ====="
    (
        # Do a charm-helpers sync where possible
        cd "charms/$charm"
        case $charm_type in
            source-zaza)
                # update/add the rebuild file to trigger a rebuild
                uuid=$(uuid)
                echo -e "# This file is used to trigger rebuilds\n# when dependencies of the charm change,\n# but nothing in the charm needs to.\n# simply change the uuid to something new\n$uuid" > ./rebuild
                ;;
            classic-zaza)
                echo "NOOP on $charm as it is a classic charm."
                ;;
            *)
                echo "UNKNOWN TYPE" && exit 1
                ;;
        esac

    )
done

