#!/bin/bash -e
# Add a lock file to the charm (assume it is a reactive charm).
# Run in the charm's root directory.
# Uses the 'add-build-lock-file' tox target.
# then cleans up afterwards.
# Run AFTER switching the charm to stable libraries (flip-master-libs-to-stable)

_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"

charm_type="$(${_dir}/what-is .)"

case $charm_type in
    source-zaza)
        # Build the charm.
        if [ ! -f src/build.lock ]; then
            # copy the add-build-lock file charmcraft in place
            cp ${_dir}/global/source-zaza/charmcraft-build-lock-file.yaml charmcraft.yaml
            tox -e build
            rm -rf .tox
            # unpack the build charm
            charm=$(grep "charm_build_name" osci.yaml | awk '{print $2}')
            unzip -p "${charm}.charm" build.lock >src/build.lock
            git checkout charmcraft.yaml
            # temporarily workaround the stable branch detection - charm-tools Bug: #606
            sed -i "s#refs/heads/master\\\\nrefs/heads/stable/#refs/heads/stable/#g" src/build.lock
        fi
        ;;
    *)
        ;;
esac
