#!/bin/bash -e
# Add the channel passed in param $1 to the batch of charms using
# ./add-channel-single.py helper.

charms="$(cat charms.txt)"
channel=$1

for charm in $charms; do
    if [ ! -d "charms/$charm" ]; then
        echo "Use ./get-charms master to clone the charm dirs first ($charm not found)"
        exit 1
    fi
done

for charm in $charms; do
    charm_type="$(./what-is charms/$charm)"
    echo "===== $charm ($charm_type) ====="
    (
        ./add-channel-single.py $charm $channel
    )
done

