#!/bin/bash -ue
# Check repo links

DISPOSITION=0
for charm in $(cat charms.txt); do

  # Handle repo url overrides if present
  if grep "^$charm|" repo-link-overrides.txt > /dev/null; then
     REPO_URL=$(grep "^$charm|" repo-link-overrides.txt | cut -f 2 -d "|")
  else
     REPO_URL="https://opendev.org/openstack/charm-${charm}"
  fi

  HTTP_CODE=$(curl --head -s -o /dev/null -w "%{http_code}" ${REPO_URL})

  # Fail on missing bug links
  if [[ $HTTP_CODE =~ ^(200|303)$ ]]; then
      FMT="\e[0m  "
  else
      FMT="\e[31m**"
      DISPOSITION=1
  fi

  echo -e "${FMT}$HTTP_CODE    $REPO_URL"
done
exit $DISPOSITION
