#!/bin/bash -ue
# Check repo links

DISPOSITION=0
charms=$(cd charms && ls -d1 *)
for charm in $charms; do

  TLP=$(grep "^project=.*" charms/$charm/.gitreview | perl -n -e'/=(.*)\// && print $1')
  REPO_URL="https://opendev.org/${TLP}/charm-${charm}"

  HTTP_CODE=$(curl --head -s -o /dev/null -w "%{http_code}" ${REPO_URL})

  # Fail on missing bug links
  if [[ $HTTP_CODE =~ ^(200|303)$ ]]; then
      FMT="\e[0m  "
  else
      FMT="\e[31m**"
      DISPOSITION=1
  fi

  echo -e "${FMT}$HTTP_CODE    $REPO_URL"
done
exit $DISPOSITION
