#!/bin/bash -ue
# Check promulgation

DISPOSITION=0
for charm in $(cat charms.txt); do
  if charm show cs:$charm -o /dev/null &> /dev/null; then
      FMT="\e[0mOK  "
  else
      FMT="\e[31m**FAIL  "
      DISPOSITION=1
  fi
  echo -e "${FMT}    $charm"
done
exit $DISPOSITION
