#!/bin/bash -e
#
# Submit gerrit reviews on changes made in local charm checkout dirs
# Generally useful for humans during batch changes (not used in OSCI).

charms="$(cat charms.txt)"
basedir="$(pwd)"

for charm in $charms; do
    cd $charm
    git commit -m "$(cat $basedir/commit-message-update-branches.txt)" && git review
    cd $basedir
    echo Sleeping breifly between reviews
    sleep 3
done
