#!/usr/bin/env bash
#
# param 1 should be the name of the charm
# param 2 should be where to put it (default pip-freeze.txt)

charm=$1
dest=${2:-pip-freeze.txt}

# find the container name
match="^charmcraft-$charm-[0-9]"
line=$(lxc list --project charmcraft --format csv | grep -e "$match")
container=$(echo $line | cut -d, -f1)
echo "container is '$container'"

if [ -z $container ];
then
    echo "Can't find $charm?"
    exit 1
fi

if [[ "$line" == *"STOPPED"* ]];
then
    lxc start --project charmcraft $container
    echo "Started $container"
fi

cmd="/root/parts/charm/build/staging-venv/bin/pip freeze"
freeze=$(lxc exec --project charmcraft $container -- $cmd)
printf "freeze is \n$freeze\n"

echo "writing freeze to $dest"
echo "$freeze" > $dest

#if [ -z $file ];
#then
    #echo "Couldn't find build.lock!"
    #exit 1
#fi

#lxc file pull --project charmcraft "$container$file" $dest
#echo "copied build.lock file."

