#!/bin/bash -e
# Clones charm branches and checks out the provided branch.

branch="$1"
all_charms="$(cat charms.txt)"
usage="usage: get-charms <master||stable/nn.nn>"

# Optionally useful for local and/or offline iterations:
# base_url="$HOME/git/release-tools.alt/"

if [ -z "$branch" ]; then
    echo $usage && exit 1
fi

for charm in $all_charms; do
    [ -d $charm ] && rm -Rf $charm

    # Handle repo url overrides if present
    if grep "^$charm|" repo-link-overrides.txt > /dev/null; then
       REPO_URL=$(grep "^$charm|" repo-link-overrides.txt | cut -f 2 -d "|")
    else
       REPO_URL="https://opendev.org/openstack/charm-${charm}"
    fi

    git clone $REPO_URL $charm
    (cd $charm; git checkout $branch)
done

