#!/usr/bin/env bash
#
# param 1 should be the name of the charm
# param 2 should be where to put it (default src/build.lock)

charm=$1
dest=${2:-src/build.lock}

# find the container name
match="^charmcraft-$charm-[0-9]"
line=$(lxc list --project charmcraft --format csv | grep -e "$match")
container=$(echo $line | cut -d, -f1)
echo "container is '$container'"

if [ -z $container ];
then
    echo "Can't find $charm?"
    exit 1
fi

if [[ "$line" == *"STOPPED"* ]];
then
    lxc start --project charmcraft $container
    echo "Started $container"
fi

file=$(lxc exec --project charmcraft $container -- find /root -name 'build.lock' | head -n1 | tr -d '\n')
echo "file is '$file'"

if [ -z $file ];
then
    echo "Couldn't find build.lock!"
    exit 1
fi

lxc file pull --project charmcraft "$container$file" $dest
echo "copied file."

