#!/bin/bash -ex
#
# A script to grant the CI bot the required permissions for pushing and publishing automatically.
# Generally must be executed as a human with existing permissions on all charms.

charms=$(cat charms.txt)

for charm in $charms; do
  charm grant cs:~openstack-charmers-next/$charm --channel stable --acl write uosci-testing-bot
  charm grant cs:~openstack-charmers/$charm --channel stable --acl write uosci-testing-bot
done
