#!/bin/bash -e
#   - Presumes the charms have been cloned and the branches have been
#       checked out in the proper dirs.
#   - $branch is used only to determine charmstore user/url and has
#       no effect on git branch currently.

branch="$2"
release="$1"
series="precise trusty xenial"
usage="usage: publish-charms series <master||stable||stable/nn.nn>"

if [ -z "$release" ] || [ -z "$series" ]; then
    echo $usage
    exit 1
fi

for release in $series; do
    charms=$(cat $release.txt)
    for charm in $charms; do
        ./push-and-publish $charm $release $branch
    done
done
