#!/bin/bash

set -x

series="$2"
charm="$1"

charm_url="~openstack-charmers/$series/$charm"

retry_command() {
    command=$@
    i=0
    attempts=10
    while [ $i -lt $attempts ]; do
        $command && break
        let "i+=1"
    done
}

echo "Pushing $charm_url"
charm_push="$(retry_command charm push $charm $charm_url)"
charm_ref="$(echo $charm_push | grep -m 1 url | awk '{ print $2 }')"

if [ -z "$charm_ref" ]; then
    echo "Failed to push charm to charm-store"
    exit 1
fi

echo "Publishing charm $charm_ref"
retry_command charm publish $charm_ref
echo "Setting global read acl"
retry_command charm grant $charm_url --acl read everyone
echo "Configuring charm options"
retry_command charm set $charm_url bugs-url=https://bugs.launchpad.net/charms/+source/$charm/+filebug \
    homepage=https://github.com/openstack/charm-$charm
