#!/bin/bash -e
#
# Do a new STABLE RELEASE from MASTER for all charms
# Note that the charms need to have been fetched using fetch-charms.py

charms=$(cd charms && ls -d1 *)
basedir="$(pwd)"
username="$2"
release="$1"
usage="usage: release-stable-charms release-name gerrit-username"

if [ -z "$release" ] || [ -z "$username" ]; then
    echo $usage
    exit 1
fi

for charm in $charms; do
    (
        cd charms/$charm
        echo "Looking at charm $charm"
        # Add the remote gerrit if needed
        $basedir/add-gerrit-remote $username
        echo "Creating stable branch for release $release"
        $basedir/create-stable-branch $release
    )
done
