#!/bin/bash -e
#
# Do a new STABLE RELEASE from MASTER for all charms

charms="$(cat charms.txt)"
basedir="$(pwd)"
username="$2"
release="$1"
usage="usage: release-stable-charms release-name gerrit-username"

if [ -z "$release" ] || [ -z "$username" ]; then
    echo $usage
    exit 1
fi

for charm in $charms; do
    [ -d $charm ] && rm -Rf $charm

    # Handle repo url overrides if present
    if grep "^$charm|" repo-link-overrides.txt > /dev/null; then
       REPO_URL=$(grep "^$charm|" repo-link-overrides.txt | cut -f 2 -d "|")
       TLP=$(grep "^$charm|" repo-link-overrides.txt | cut -f 4 -d "/")
    else
       REPO_URL="https://opendev.org/openstack/charm-${charm}"
       TLP=openstack
    fi

    git clone $REPO_URL $charm
    (
        cd $charm
        echo "Adding gerrit remote"
        git remote add gerrit ssh://${username}@review.openstack.org:29418/${TLP}/charm-${charm}.git
        echo "Creating stable branch for release $release"
        $basedir/create-stable-branch $release
    )
done
