#!/bin/bash -e
# Remove the channel from the bundles of all of the charms using the
# ./update-channel-single.py helper.

charms=$(cd charms && ls -d1 *)

for charm in $charms; do
    charm_type="$(./what-is charms/$charm)"
    echo "===== $charm ($charm_type) ====="
    (
        ./update-channel-single.py --remove-channel charms/$charm
    )
done

