#!/bin/bash -e
#
# Post-Release Repo Tasks
#   - Flip stable charm-helpers and Amulet bits.
#   - Update .gitreview with new stable branch name.

release="$1"

if [ -z "$release" ]; then
    echo "Please provide release as only parameter"
    exit 1
fi

git checkout -b ${release}-updates origin/stable/${release}

grep -q defaultbranch .gitreview || {
    echo -e "\ndefaultbranch=stable/$release" >> .gitreview
    git add .gitreview
}

if [ -f tests/basic_deployment.py ]; then
    echo "Updating amulet tests to refer to stable branches"
    sed -i 's/stable=False/stable=True/g' tests/basic_deployment.py
    git add tests/basic_deployment.py
fi

if [ -f src/tests/basic_deployment.py ]; then
    echo "Updating amulet tests to refer to stable branches src"
    sed -i 's/stable=False/stable=True/g' src/tests/basic_deployment.py
    git add src/tests/basic_deployment.py
fi

if [ -d src/tests/bundles ]; then
    echo "Updating zaza tests to refer to stable branches src"
    for filename in $(find src/tests/bundles | grep yaml); do
        sed -i 's#cs:~openstack-charmers-next/#cs:#g' $filename
        # Quagga actually needs to be in ~openstack-charmers-next
        sed -i 's#cs:quagga#cs:~openstack-charmers-next/quagga#g' $filename
    done
    git add src/tests/bundles
fi

if [ -d tests/bundles ]; then
    echo "Updating zaza tests to refer to stable branches src"
    for filename in $(find tests/bundles | grep yaml); do
        sed -i 's#cs:~openstack-charmers-next/#cs:#g' $filename
    done
    git add tests/bundles
fi

for ch in charm-helpers-hooks.yaml charm-helpers-tests.yaml; do
    if [ -f $ch ]; then
        sed -i "s/https\:\/\/github.com\/juju\/charm-helpers$/https\:\/\/github.com\/juju\/charm-helpers\@stable\/${release}/g" $ch
        git add $ch
    fi
    if [ -f src/$ch ]; then
        sed -i "s/https\:\/\/github.com\/juju\/charm-helpers$/https\:\/\/github.com\/juju\/charm-helpers\@stable\/${release}/g" src/$ch
        git add src/$ch
    fi
done
