#!/bin/bash -e
#
# Post-Release Repo Tasks
#   - Flip stable charm-helpers and Zaza bits.
#   - Update .gitreview with new stable branch name.

release="$1"
branch="$2"

if [ -z "$branch" ]; then
    echo "Please provide release and branch parameters"
    echo "usage: stable-branch-updates release branch"
    echo "e.g.   stable-branch-updates yoga jammy"
    echo " means 'stable/yoga' for libs, and 'stable/jammy' for this charm"
    exit 1
fi

git fetch --all
git checkout -b ${release}-updates origin/stable/${branch}

grep -q defaultbranch .gitreview || {
    echo -e "\ndefaultbranch=stable/$branch" >> .gitreview
    git add .gitreview
}

for ch in charm-helpers-hooks.yaml charm-helpers-tests.yaml; do
    if [ -f $ch ]; then
        sed -i "s/https\:\/\/github.com\/juju\/charm-helpers$/https\:\/\/github.com\/juju\/charm-helpers\@stable\/${release}/g" $ch
        git add $ch
    fi
    if [ -f src/$ch ]; then
        sed -i "s/https\:\/\/github.com\/juju\/charm-helpers$/https\:\/\/github.com\/juju\/charm-helpers\@stable\/${release}/g" src/$ch
        git add src/$ch
    fi
done

if [ -f src/layer.yaml ]; then
    set +e
        grep -q charms.openstack.git@stable src/wheelhouse.txt 2>/dev/null || {
            echo "Updating charm wheelhouse, with stable 'charms.openstack'"
            sed -i "s#openstack/charms.openstack.git#openstack/charms.openstack.git@stable/$release#g" src/wheelhouse.txt
        }
        grep -q charm-helpers.git@stable src/wheelhouse.txt 2>/dev/null || {
            echo "Updating charm wheelhouse, with stable 'charmhelpers'"
            sed -i "s#juju/charm-helpers.git#juju/charm-helpers.git@stable/${release}#g" src/wheelhouse.txt
        }
        grep -q charms.openstack.git@stable tests-requirements.txt 2>/dev/null || {
            echo "Updating test-requirements.txt in repository with stable charms.openstack"
            sed -i "s#openstack/charms.openstack.git#openstack/charms.openstack.git@stable/$release#g" test-requirements.txt
        }
        grep -q zaza-openstack-tests.git@stable src/tests-requirements.txt 2>/dev/null || {
            echo "Updating src/test-requirements.txt in repository with stable Zaza"
            sed -i "s#openstack-charmers/zaza.git#openstack-charmers/zaza.git@stable/$release#g" src/test-requirements.txt
            sed -i "s#openstack-charmers/zaza-openstack-tests.git#openstack-charmers/zaza-openstack-tests.git@stable/$release#g" src/test-requirements.txt
        }
    set -e
else
    set +e
        grep -q zaza-openstack-tests.git@stable tests-requirements.txt 2>/dev/null || {
            echo "Updating test-requirements.txt in repository with stable Zaza"
            sed -i "s#openstack-charmers/zaza.git#openstack-charmers/zaza.git@stable/$release#g" test-requirements.txt
            sed -i "s#openstack-charmers/zaza-openstack-tests.git#openstack-charmers/zaza-openstack-tests.git@stable/$release#g" test-requirements.txt
        }
    set -e
fi
