#!/bin/bash -e
#
# Apply stable-branch-updates to all charms (typically post-release charm-helper and amulet stable bit flips).

charms="$(cat charms.txt)"
basedir="$(pwd)"
username="$2"
release="$1"
usage="usage: update-stable-charms release-name"

if [ -z "$release" ]; then
    echo $usage
    exit 1
fi

for charm in $charms; do
    [ -d charms/$charm ] && rm -Rf charms/$charm

    # Handle repo url overrides if present
    if grep "^$charm|" repo-link-overrides.txt > /dev/null; then
       REPO_URL=$(grep "^$charm|" repo-link-overrides.txt | cut -f 2 -d "|")
    else
       REPO_URL="https://opendev.org/openstack/charm-${charm}"
    fi

    git clone $REPO_URL charms/$charm
    (
        cd charms/$charm
        $basedir/stable-branch-updates $release
    )
done
