#!/bin/bash -e
#
#  Update requirements in all charms, with some exceptions.
#
#  Remove tests/charmhelpers in favor of venv charmhelpers.
#
#  Propose gerrit reviews.
#
#  Optionally avoid the gerrit review by exporting env var DRY_RUN=True
#
#    - For src charms:
#        - Updates src/tox.ini  [testenv] section
#        - Does NOT (yet) update ./tox.ini for source charms as they differ.
#
#    - For classic charms:
#        - Updates ./tox.ini    [testenv] section

gerrit_topic="update-tox-testenv"

charms="$(cat charms.txt)"
src_charms="$(cat source-charms.txt)"
basedir="$(pwd)"
branch="$1"
commit_msg_file="$basedir/commit-msg-tox-testenv.txt"
usage="usage: update-tox-testenv-section <master||stable/nn.nn>

This will create gerrit reviews using commit-msg-tox-testenv.txt!
Set environment variable in advance if that should be avoided:
  export DRY_RUN=True
"

if [ -z "$branch" ]; then
    echo -e "$usage"
    exit 1
fi

# Expect user to have git config ready for gerrit use
git config --get gitreview.username || ( echo " ! Not set: gitreview.username git config option"; echo -e "$usage"; exit 1 )


commit_msg="$(cat $commit_msg_file ||:)"
if [ -z "$commit_msg" ]; then
    echo " ! $commit_msg_file not found or empty."
    exit 1
fi


function insert_warn_line(){
  WARN_TXT="# This file should not be modified in the charm repo, as it is controlled globally by release-tools."
  sed -i "1i$WARN_TXT" $1
}


function git_get(){
  [ -d $2 ] && rm -Rf $2
  (
    git clone $1 $2
    cd $2
    git checkout $3
  )
}


function git_review(){
  if [ "${DRY_RUN^^}" == "TRUE" ]; then
    echo " . Not proposing gerrit (dry run)."
    return 0
  fi
  (
    echo " . Submitting gerrit review for $charm"
    echo " (NOT REALLY YET")
#    git review
  )
}

# Get bot-control tools
git_get https://github.com/openstack-charmers/bot-control bc-tools master


function update_tox_testenv_section(){
    pwd
    ./bc-tools/tools/ini-splice $1 replace-section testenv with $2
}


for charm in $charms; do
  (
    git_get https://github.com/openstack/charm-$charm $charm $branch

    if [[ $src_charms == *"$charm"* ]]; then
      # src charms
      update_tox_testenv_section $basedir/$charm/src/tox.ini $basedir/global/source-charms/src/tox.ini
      update_tox_testenv_section $basedir/$charm/tox.ini $basedir/global/source-charms/tox.ini
      insert_warn_line $basedir/$charm/src/tox.ini
      insert_warn_line $basedir/$charm/tox.ini
    else
      # classic charms
      update_tox_testenv_section $basedir/$charm/tox.ini $basedir/global/classic-charms/tox.ini
      insert_warn_line $basedir/$charm/tox.ini
    fi

    cd $charm
    git add .
    git status -s
    git commit -F $commit_msg_file
    git_review
  )
done
