#!/bin/bash -e
#
# Apply stable-branch-updates to all charms (typically post-release charm-helper and zaza stable bit flips).
# Note that the charms need to have been fetched using fetch-charms.py

charms=$(cd charms && ls -d1 *)
basedir="$(pwd)"
username="$2"
release="$1"
branch="$3"
usage="usage: update-stable-charms release-name username branch"

if [ -z "$branch" ]; then
    echo $usage
    exit 1
fi

for charm in $charms; do
    (
        cd charms/$charm
        echo "Looking at charm $charm"
        # get the url for the charm.
        $basedir/add-gerrit-remote $username
        $basedir/stable-branch-updates $release $branch
    )
done
