#!/bin/bash -e
# Update the charms metadata with a command line "add" "groovy"

charms=$(cd charms && ls -d1 *)
cmd=$1
shift
params=$@

if [ ! -d ".tox/py3" ]; then
    tox -e py3 --notest
fi


for charm in $charms; do
    echo "===== $charm ====="
    .tox/py3/bin/python _update-metadata.py $charm $cmd $params
done

