#!/bin/bash -e
#
# Apply stable-branch-updates to all charms (typically post-release charm-helper and zaza stable bit flips).
# Note that the charms need to have been fetched using fetch-charms.py

charms=$(cd charms && ls -d1 *)
basedir="$(pwd)"
username="$2"
release="$1"
usage="usage: update-stable-charms release-name"

if [ -z "$release" ]; then
    echo $usage
    exit 1
fi

for charm in $charms; do
    (
        cd charms/$charm
        echo "Looking at charm $charm"
        # get the url for the charm.
        TLP=$(grep "^project=.*" .gitreview | perl -n -e'/=(.*)\// && print $1')
        REPO_URL="https://opendev.org/$TLP/charm-${charm}"

        git remote | grep gerrit || {
            echo "Adding gerrit remote"
            git remote add gerrit ssh://${username}@review.openstack.org:29418/${TLP}/charm-${charm}.git
        }
        $basedir/stable-branch-updates $release
    )
done
