#!/bin/bash -e
#
#  Update Amulet test definitions
#
#  This script is likely only relevant for the tasks necessary at a
#  point in time.  Committed to repo for reference anyway, to be
#  improved upon or adjusted for later needs.

charms="$(cat charms.txt)"
src_charms="$(cat source-charms.txt)"
basedir="$(pwd)"
branch="$1"

gerrit_topic="update-amulet-defs-bionic"
commit_msg_file="$basedir/commit-message-amulet-defs.txt"

all_params="$@"
if [[ "$all_params" == *--amend* ]]; then
  AMEND="True"
fi
if [[ "$all_params" == *--no-review* ]]; then
  NO_REVIEW="True"
fi
if [[ "$all_params" == *--force-review* ]]; then
  FORCE_REVIEW="True"
fi
if [[ "$all_params" == *--rebase-master* ]]; then
  REBASE_MASTER="True"
fi
if [[ "$all_params" == *--ch-sync-legacy* ]]; then
  CH_SYNC="True"
fi

usage="usage: update-amulet-defs <master||stable/nn.nn>

USAGE EXAMPLES

Clone repos, check out the master branch, make changes and
submit gerrit reviews:
  ./update-amulet-defs master

Clone repos, check out the master branch, performa a legacy
charm-helper sync, make changes and submit gerrit reviews:
  ./update-amulet-defs master --ch-sync-legacy

Clone repos, check out the master branch, make changes
but do not actually submit a gerrit review:
  ./update-amulet-defs master --no-review

Re-use local checkout, amend commits and add patchset to
the existing gerrit review:
  ./update-amulet-defs master --amend

Re-use local checkout, rebase with master, amend commits
and add patchset to the existing gerrit review:
  ./update-amulet-defs master --amend --rebase-master

Re-use local checkout, rebase with master, amend commits
and add patchset to the existing gerrit review even if
no changes detected in the repo.  Useful if manually
committing changes in the local repo outside this script.
  ./update-amulet-defs master --amend --rebase-master --force-review

Re-use local checkout, amend commits for adding to the review,
but do not actually submit a gerrit review:
  ./update-amulet-defs master --amend --no-review
"

if [ -z "$branch" ]; then
    echo -e "$usage"
    exit 1
fi

# Expect user to have git config ready for gerrit use
git config --get gitreview.username || ( echo " ! Not set: gitreview.username git config option"; echo -e "$usage"; exit 1 )

commit_msg="$(cat $commit_msg_file ||:)"
if [ -z "$commit_msg" ]; then
    echo " ! $commit_msg_file not found or empty."
    exit 1
fi


function git_get(){
  (
  if [[ "${AMEND^^}" != "TRUE" ]] && [[ ! -d $2 ]]; then
    echo " + Clone $1 -> $2"
    git clone $1 $2
    cd $2
    git checkout $3
  elif [[ "${AMEND^^}" != "TRUE" ]] && [[ -d $2 ]]; then
    echo " ! Dir exists: $2.  Consider running 'make clean' or using --amend."
    exit 1
  else
    echo " . Re-using checkout dir $2"
    cd $2
    git branch -v
  fi
  )
}


function git_review(){
  if [ "${NO_REVIEW^^}" == "TRUE" ]; then
    echo " . Not proposing gerrit (dry run)."
  elif [ "${FORCE_REVIEW^^}" != "TRUE" ]; then
    echo " . Submitting gerrit review for $charm"
    git review
  elif [ "${FORCE_REVIEW^^}" == "TRUE" ]; then
    echo " . Submitting gerrit review for $charm (non-fatal on failure)"
    git review ||:
  else
    echo " ! Unknown condition in git_review"
    exit 1
  fi
}


for charm in $charms; do
  echo "===== $charm ====="
  (
    git_get https://github.com/openstack/charm-$charm $charm $branch
    cd $charm

    # Set file locations depending on charm type
    charm_dir="$basedir/$charm"
    if grep "^$charm$" ../zaza-charms.txt; then
      echo "Skipping zaza charm"
      continue
    elif grep "^$charm$" ../source-charms.txt; then
      # src charms
      echo " . source charm"
      tests_dir="$basedir/$charm/src/tests"
	 test_tox_file="$basedir/$charm/src/tox.ini"
    else
      # classic charms
      echo " . classic charm"
      tests_dir="$basedir/$charm/tests"
	 test_tox_file="$basedir/$charm/tox.ini"
    fi

    x_q_dest_file="$tests_dir/gate-basic-xenial-queens"
    b_q_src_file="$tests_dir/dev-basic-bionic-queens"
    b_q_dest_file="$tests_dir/gate-basic-bionic-queens"

    x_m_src_file="$tests_dir/gate-basic-xenial-mitaka"
    x_o_src_file="$tests_dir/gate-basic-xenial-ocata"

    p_i_del_file="$tests_dir/*precise*"
    y_n_del_file="$tests_dir/*yakkety*"
    z_o_del_file="$tests_dir/*zesty*"


    if [[ ! -f $b_q_dest_file ]] && [[ ! -f $b_q_src_file ]] && [[ -f $x_m_src_file ]]; then
      # Add bionic amulet tests
      echo "Creating bionic-queens test."
      cp -fv $x_m_src_file $b_q_dest_file
      sed -e "s_mitaka_queens_g" -i $b_q_dest_file
      sed -e "s_Mitaka_Queens_g" -i $b_q_dest_file
      sed -e "s_xenial_bionic_g" -i $b_q_dest_file
      sed -e "s_Xenial_Bionic_g" -i $b_q_dest_file
      chmod +x $b_q_dest_file
    elif [[ -f $b_q_src_file ]]; then
      echo "Moving bionic-queens test to gate."
      git mv $b_q_src_file $b_q_dest_file
    fi

    if [[ ! -f $x_q_dest_file ]] && [[ -f $x_o_src_file ]]; then
      echo "Creating xenial-queens test"
      cp -fv $x_o_src_file $x_q_dest_file
      sed -e "s_ocata_queens_g" -i $x_q_dest_file
      sed -e "s_Ocata_Queens_g" -i $x_q_dest_file
      chmod +x $x_q_dest_file
    fi

    # Enable and disable edges
    chmod -v +x ${tests_dir}/dev-*     ||:
    chmod -v +x ${tests_dir}/*newton*  ||:
    chmod -v +x ${tests_dir}/*ocata*   ||:
    #chmod -v +x ${tests_dir}/*pike*   ||:
    chmod -v +x ${tests_dir}/*queens*   ||:
    chmod -v +x ${tests_dir}/*bionic*   ||:
    #chmod -v +x ${tests_dir}/*artful* ||:

    # Fix hashbangs if necessary
    find ${tests_dir} -maxdepth 1 -type f | xargs sed -e "s_#\!/usr/bin/python\$_#\!/usr/bin/env python_g" -i
    find ${tests_dir} -maxdepth 1 -type f | xargs sed -e "s_#\!/usr/bin/python3\$_#\!/usr/bin/env python3_g" -i

    # Remove tests
    git rm -f $p_i_del_file ||:
    git rm -f $y_n_del_file ||:
    git rm -f $z_o_del_file ||:

    # Remove deprecated series
    metadata=$(find $charm_dir -name "metadata.yaml")
    echo " . metadata file: $metadata"
    sed -i "/ - precise/d" $metadata  ||:
    sed -i "/ - yakkety/d" $metadata  ||:
    sed -i "/ - zesty/d" $metadata    ||:

    # Add current dev series
    if ! grep " - bionic" $metadata; then
      sed -e "s_  - xenial_  - xenial\n  - bionic_g" $metadata -i
    fi

    if ! grep "bionic" $metadata; then
      echo " ! No bionic in $metadata"
      exit 1
    fi

    if ! grep "artful" $metadata; then
      echo " ! No artful in $metadata"
      exit 1
    fi

    # Update smoke test target
    echo "Update smoke test target"
    sed -i -e "s/bundletester -vl DEBUG -r json -o func-results.json gate-basic-xenial.* --no-destroy/bundletester -vl DEBUG -r json -o func-results.json gate-basic-bionic-queens --no-destroy/g" $test_tox_file



    # Optionally rebase with master
    if [[ "${REBASE_MASTER^^}" == "TRUE" ]]; then
      (
        git checkout master
        git pull
        git checkout $gerrit_topic || git checkout -b $gerrit_topic
        git rebase master
      )
    fi

    # Optionally do legacy-style charm-helper sync
    if [[ "${CH_SYNC^^}" == "TRUE" ]] && [[ -f 'Makefile' ]]; then
      echo " + Doing legacy-style charm-helper sync on $charm"
      make sync
    else
      echo " . No legacy-style charm-helper sync available for $charm"
    fi

    # Commit if there are changes, or optionally commit even if no changes
    git_status="$(git status -s)"
    if [[ "${FORCE_REVIEW^^}" == "TRUE" ]]; then
      git_status="True"
    fi
    if [[ "${AMEND^^}" != "TRUE" ]] && [[ -n "$git_status" ]]; then
      git checkout -b $gerrit_topic
      git add .
      git commit -F $commit_msg_file
      git_review
    elif [[ "${AMEND^^}" == "TRUE" ]] && [[ -n "$git_status" ]]; then
      git checkout $gerrit_topic || git checkout -b $gerrit_topic
      git add .
      git commit --amend --no-edit
      git_review
    else
      echo " - No changes for $charm, skipping git review."
    fi
  )
done
