#!/bin/bash -e
charms=$(cd ../charms && ls -d1 *)

for charm in $charms; do
    echo "===== $charm ====="
    (
        cd ../charms/$charm
        grep -qxF '*.charm' .gitignore || echo '*.charm' >> .gitignore
    )
done
