#!/bin/bash

# Note that this needs to be run in the root for the charm directory

# run this script in the root of the charm directory

script_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"
repo_dir="$script_dir/.."
worktree_branch="stable/ussuri"
ceph_release="nautilus"
openstack_release="train"

ceph_branch="nautilus"
openstack_branch="train"
mysql_branch="5.7"
hacluster_branch="bionic"
rabbitmq_server_branch="bionic"
vault_branch="1.6"

# bring in the common functions
source "$script_dir/utils.sh"


# update metadata // called in context of directory with metadata
# param 1 is the file to update
function update_metadata {
    local metafile=$1
    sed -i '/- trusty/d' $metafile
    sed -i '/- xenial/d' $metafile
    sed -i '/- focal/d' $metafile
    sed -i '/- groovy/d' $metafile
    sed -i '/- impish/d' $metafile
    sed -i '/- hirsute/d' $metafile
}

function update_osci {
    local oscifile=$1
    sed -i 's/- charm-yoga-unit-jobs/- charm-unit-jobs-py36/1' $oscifile
    sed -i 's/- charm-unit-jobs.*/- charm-unit-jobs-py36/1' $oscifile
    sed -i '/- .*ussuri.*d/' $oscifile
    sed -i '/- .*victoria.*d/' $oscifile
    sed -i '/- .*wallaby.*d/' $oscifile
    sed -i '/- .*xena.*d/' $oscifile
    sed -i '/- .*yoga.*d/' $oscifile
    sed -i '/- .*xenial.*/d' $oscifile
    sed -i '/- .*hirsute.*/d' $oscifile
    sed -i '/- .*impish.*/d' $oscifile
    sed -i '/- .*focal.*/d' $oscifile
    sed -i '/- .*groovy.*/d' $oscifile

    # ensure that charm-train-functional-jobs is present
    sed -i '/- charm-functional-jobs/d' $oscifile
    grep -q "charm-train-functional-jobs" $oscifile || {
        change="\      - charm-train-functional-jobs"
        sed -i "/- charm-unit-jobs-py36/a $change" $oscifile
    }
    grep -q "charm-stein-functional-jobs" $oscifile || {
        change="\      - charm-stein-functional-jobs"
        sed -i "/- charm-unit-jobs-py36/a $change" $oscifile
    }
    grep -q "charm-rocky-functional-jobs" $oscifile || {
        change="\      - charm-rocky-functional-jobs"
        sed -i "/- charm-unit-jobs-py36/a $change" $oscifile
    }
    grep -q "charm-queens-functional-jobs" $oscifile || {
        change="\      - charm-queens-functional-jobs"
        sed -i "/- charm-unit-jobs-py36/a $change" $oscifile
    }
}

function update_tests_yaml {
    local yamlfile=$1
    sed -i '/- .*ussuri/d' $yamlfile
    sed -i '/- .*victoria/d' $yamlfile
    sed -i '/- .*wallaby/d' $yamlfile
    sed -i '/- .*xena/d' $yamlfile
    sed -i '/- .*yoga/d' $yamlfile
    sed -i '/- .*impish/d' $yamlfile
    sed -i '/- .*focal/d' $yamlfile
    sed -i '/- .*groovy/d' $yamlfile
    sed -i '/- .*hirsute/d' $yamlfile
    sed -i '/- .*xenial/d' $yamlfile
}

function remove_bundles {
    local bundles_dir=$1
    (
        cd $bundles_dir
        rm *ussuri*.yaml
        rm *victoria*.yaml
        rm *wallaby*.yaml
        rm *xena*.yaml
        rm *yoga*.yaml
        rm *focal*.yaml
        rm *groovy*.yaml
        rm *hirsute*.yaml
        rm *impish*.yaml
        rm *xenial*.yaml
        rm *trusty*.yaml
    )
}

function update_bundles {
    local charm_dir=$1
    (
        cd $charm_dir
        # remove any existing channel specs
        $repo_dir/update-channel-single.py --log DEBUG \
            --remove-channel \
            --disable-local-overlay
        # set all the branches to latest/edge and ch: prefixes
        $repo_dir/update-channel-single.py --log DEBUG --branch master \
            --ensure-charmhub --enforce-edge
        # Then overwrite with branches appropirate to ceph-pacific
        $repo_dir/update-channel-single.py --log DEBUG \
            --branch stable/$openstack_branch \
            --branch stable/$mysql_branch   \
            --branch stable/$hacluster_branch \
            --branch stable/$vault_branch \
            --branch stable/$rabbitmq_server_branch \
            --branch stable/$ceph_branch \
            --set-local-charm \
            --enforce-edge
    )
}


# update .zuul.conf file
# stable/21.10 looks like:
#- project:
#    templates:
#      - python35-charm-jobs
#      - openstack-python3-ussuri-jobs
#      - openstack-cover-jobs
#
# but it needs to be:
#-project:
#   templates:
#     - openstack-python38-jobs
#     - openstack-tox-pep8
#     - openstack-cover-jobs
# run this in the directory of the charm to update
function ensure_zuul_conf {
    cp $script_dir/train_zuul.yaml .zuul.yaml
}


# fix up the build.lock file for a reactive charm.
# file is passed in $1
function fix_lock_file {
    local filename="$1"
    $repo_dir/update-build-lock.py \
        --file $filename \
        --type python_module \
        --package Tempita \
        delete
    $repo_dir/update-build-lock.py \
        --file $filename \
        --type python_module \
        --package charmhelpers \
        modify --spec='{"branch": "stable/train", "version": "13fc2babe1999df87aaf149c549d8140289837a3"}'
    $repo_dir/update-build-lock.py \
        --file $filename \
        --type python_module \
        --package charms.openstack \
        modify --spec='{"branch": "stable/train", "version": "10627ee5f991c268f174d6d100e218a0e1867af1"}'
}


## remove py39 and py310 as they are not needed.
function fix_up_tox_file {
    local tox_file=tox.ini
    sed -i "/^\[testenv:py39\]/,+4d" $tox_file
    sed -i "/^\[testenv:py310\]/,+4d" $tox_file
}

## fix the tempest import of py36
function fix_up_tempest_import {
    local test_file=test-requirements.txt
    local found="$(grep tempest $test_file ||:)"
    if [[ -n "$found" ]]; then
        # do the tempest changes
        sed -i "s/egg=tempest;python_version>='3.6'/egg=tempest;python_version>='3.8'/g" $test_file
        grep -q "tempest<31.0.0;python_version<'3.8'" $test_file || {
            sed -i "/python_version>='3.8'/a tempest<31.0.0;python_version<'3.8'" $test_file
        }
    fi
}


# Note that this needs to be run in the root for the charm directory
charm_type="$($repo_dir/what-is .)"
echo "===== $charm_type ====="
case $charm_type in
    source-zaza)
        ensure_git_branch $openstack_release
        ensure_gitignore_charm
        charmcraft_source $worktree_branch
        $script_dir/update-charmcraft-train.py charmcraft.yaml
        $script_dir/ensure-osci-vars-charmcraft.py osci.yaml
        ln -s src/metadata.yaml
        update_metadata src/metadata.yaml
        update_osci osci.yaml
        update_tests_yaml src/tests/tests.yaml
        remove_bundles src/tests/bundles
        update_bundles .
        add_rename $worktree_branch
        add_build_requirements $worktree_branch
        ensure_tox_source $worktree_branch
        fix_up_tox_file
        ensure_git_review $openstack_release
        ensure_libs_source $openstack_release $ceph_release
        ensure_src_tr_tox
        ensure_zuul_conf
        fix_lock_file src/build.lock
        ensure_pyparsing_pin
        fix_up_tempest_import
        ;;
    classic-zaza)
        ensure_git_branch $openstack_release
        ensure_gitignore_charm
        charmcraft_classic $worktree_branch
        $script_dir/update-charmcraft-train.py charmcraft.yaml
        $script_dir/ensure-osci-vars-charmcraft.py osci.yaml
        update_metadata metadata.yaml
        update_osci osci.yaml
        update_tests_yaml tests/tests.yaml
        remove_bundles tests/bundles
        update_bundles .
        add_rename $worktree_branch
        add_build_requirements $worktree_branch
        ensure_tox_classic $worktree_branch
        fix_up_tox_file
        ensure_git_review $openstack_release
        ensure_libs_classic $openstack_release $ceph_release
        ensure_zuul_conf
        ensure_pyparsing_pin
        fix_up_tempest_import
        ;;
    *)
        echo "It must be a charmcraft native one."
        $script_dir/update-charmcraft-train.py charmcraft.yaml
        $script_dir/ensure-osci-vars-charmcraft.py osci.yaml
        ensure_git_branch $openstack_release
        ensure_git_review $openstack_release
        ensure_gitignore_charm
        update_osci osci.yaml
        update_metadata metadata.yaml
        update_tests_yaml src/tests/tests.yaml
        remove_bundles src/tests/bundles
        update_bundles .
        add_rename $worktree_branch
        ensure_libs_ops $openstack_release $ceph_release
        ensure_zuul_conf
        ensure_pyparsing_pin
        fix_up_tempest_import
        ;;
esac
