#!/bin/bash

# Note that this needs to be run in the root for the charm directory

# run this script in the root of the charm directory

script_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"
repo_dir="$script_dir/.."
worktree_branch="stable/yoga"
ceph_release="pacific"
openstack_release="victoria"

# bring in the common functions
source "$script_dir/utils.sh"


# update metadata // called in context of directory with metadata
# param 1 is the file to update
function update_metadata {
    local metafile=$1
    sed -i '/- trusty/d' $metafile
    sed -i '/- xenial/d' $metafile
    sed -i '/- bionic/d' $metafile
    sed -i '/- groovy/d' $metafile
    sed -i '/- impish/d' $metafile
    sed -i '/- hirsute/d' $metafile
}

function update_osci {
    local oscifile=$1
    sed -i 's/- charm-yoga-unit-jobs/- charm-unit-jobs-py38/1' $oscifile
    sed -i 's/- charm-unit-jobs.*/- charm-unit-jobs-py38/1' $oscifile
    sed -i '/- .*queens.*/d' $oscifile
    sed -i '/- .*rocky/d' $yamlfile
    sed -i '/- .*stein.*/d' $oscifile
    sed -i '/- .*train.*/d' $oscifile
    sed -i '/- .*wallaby.*d/' $oscifile
    sed -i '/- .*xena.*d/' $oscifile
    sed -i '/- .*yoga.*d/' $oscifile
    sed -i '/- .*xenial.*/d' $oscifile
    sed -i '/- .*bionic.*/d' $oscifile
    sed -i '/- .*hirsute.*/d' $oscifile
    sed -i '/- .*impish.*/d' $oscifile
    sed -i '/- .*groovy.*/d' $oscifile

    # ensure that charm-ussuri-functional-jobs and charm-victora-functional-jobs
    # is present
    sed -i '/- charm-functional-jobs/d' $oscifile
    grep -q "charm-victoria-functional-jobs" $oscifile || {
        change="\      - charm-victoria-functional-jobs"
        sed -i "/- charm-unit-jobs-py38/a $change" $oscifile
    }
    grep -q "charm-ussuri-functional-jobs" $oscifile || {
        change="\      - charm-ussuri-functional-jobs"
        sed -i "/- charm-unit-jobs-py38/a $change" $oscifile
    }
}

function update_tests_yaml {
    local yamlfile=$1
    sed -i '/- .*mitaka/d' $yamlfile
    sed -i '/- .*queens/d' $yamlfile
    sed -i '/- .*rocky/d' $yamlfile
    sed -i '/- .*stein/d' $yamlfile
    sed -i '/- .*train/d' $yamlfile
    sed -i '/- .*wallaby/d' $yamlfile
    sed -i '/- .*xena/d' $yamlfile
    sed -i '/- .*yoga/d' $yamlfile
    sed -i '/- .*impish/d' $yamlfile
    sed -i '/- .*groovy/d' $yamlfile
    sed -i '/- .*hirsute/d' $yamlfile
    sed -i '/- .*xenial/d' $yamlfile
    sed -i '/- .*bionic/d' $yamlfile
}

function remove_bundles {
    local bundles_dir=$1
    (
        cd $bundles_dir
        rm *queens*.yaml
        rm *rocky*.yaml
        rm *stein*.yaml
        rm *train*.yaml
        rm *wallaby*.yaml
        rm *xena*.yaml
        rm *yoga*.yaml
        rm *groovy*.yaml
        rm *hirsute*.yaml
        rm *impish*.yaml
        rm *xenial*.yaml
        rm *bionic*.yaml
        rm *trusty*.yaml
    )
}

function update_bundles {
    local charm_dir=$1
    (
        cd $charm_dir
        # remove any existing channel specs
        $repo_dir/update-channel-single.py --log DEBUG \
            --remove-channel \
            --disable-local-overlay \
            --set-local-charm
        # set all the branches to latest/edge and ch: prefixes
        $repo_dir/update-channel-single.py --log DEBUG --branch master --ensure-charmhub
        # Then overwrite with branches appropirate to ceph-pacific
        $repo_dir/update-channel-single.py --log DEBUG \
            --branch stable/$openstack_release \
            --branch stable/20.03 \
            --branch stable/focal \
            --branch stable/1.7 \
            --branch stable/jammy \
            --branch stable/$ceph_release
    )
}


# update .zuul.conf file
# stable/21.10 looks like:
#- project:
#    templates:
#      - python35-charm-jobs
#      - openstack-python3-ussuri-jobs
#      - openstack-cover-jobs
#
# but it needs to be:
#-project:
#   templates:
#     - openstack-python38-jobs
#     - openstack-tox-pep8
#     - openstack-cover-jobs
# run this in the directory of the charm to update
function ensure_zuul_conf {
    cp $script_dir/victoria_zuul.yaml .zuul.yaml
}


# fix up the build.lock file for a reactive charm.
# file is passed in $1
function fix_lock_file {
    local filename="$1"
    $repo_dir/update-build-lock.py \
        --file $filename \
        --type python_module \
        --package Tempita \
        delete
    $repo_dir/update-build-lock.py \
        --file $filename \
        --type python_module \
        --package charmhelpers \
        modify --spec='{"branch": "stable/victoria", "version": "df2e33ed634200de1d02d7e5f1baaf80f22a6315"}'
    $repo_dir/update-build-lock.py \
        --file $filename \
        --type python_module \
        --package charms.openstack \
        modify --spec='{"branch": "stable/victoria", "version": "10627ee5f991c268f174d6d100e218a0e1867af1"}'
}


# Note that this needs to be run in the root for the charm directory
charm_type="$($repo_dir/what-is .)"
echo "===== $charm_type ====="
case $charm_type in
    source-zaza)
        ensure_git_branch $openstack_release
        ensure_gitignore_charm
        charmcraft_source $worktree_branch
        $script_dir/update-charmcraft-victoria.py charmcraft.yaml
        $script_dir/ensure-osci-vars-charmcraft.py osci.yaml
        ln -s src/metadata.yaml
        update_metadata src/metadata.yaml
        update_osci osci.yaml
        update_tests_yaml src/tests/tests.yaml
        remove_bundles src/tests/bundles
        update_bundles .
        add_rename $worktree_branch
        add_build_requirements $worktree_branch
        ensure_tox_source $worktree_branch
        ensure_git_review $openstack_release
        ensure_libs_source $openstack_release $ceph_release
        ensure_src_tr_tox
        ensure_zuul_conf
        fix_lock_file src/build.lock
        ensure_pyparsing_pin
        ;;
    classic-zaza)
        ensure_git_branch $openstack_release
        ensure_gitignore_charm
        charmcraft_classic $worktree_branch
        $script_dir/update-charmcraft-victoria.py charmcraft.yaml
        $script_dir/ensure-osci-vars-charmcraft.py osci.yaml
        update_metadata metadata.yaml
        update_osci osci.yaml
        update_tests_yaml tests/tests.yaml
        remove_bundles tests/bundles
        update_bundles .
        add_rename $worktree_branch
        add_build_requirements $worktree_branch
        ensure_tox_classic $worktree_branch
        ensure_git_review $openstack_release
        ensure_libs_classic $openstack_release $ceph_release
        ensure_zuul_conf
        ensure_pyparsing_pin
        ;;
    *)
        echo "It must be a charmcraft native one."
        $script_dir/update-charmcraft-victoria.py charmcraft.yaml
        $script_dir/ensure-osci-vars-charmcraft.py osci.yaml
        ensure_git_branch $openstack_release
        ensure_git_review $openstack_release
        ensure_gitignore_charm
        update_osci osci.yaml
        update_metadata metadata.yaml
        update_tests_yaml src/tests/tests.yaml
        remove_bundles src/tests/bundles
        update_bundles .
        add_rename $worktree_branch
        ensure_libs_ops $openstack_release $ceph_release
        ensure_zuul_conf
        ensure_pyparsing_pin
        ;;
esac
